### ISSUE TITLE
Proposal Checklist

### ISSUE THREAD

**Issue by ErikElliott-ynp** [andrewc2695/dotify#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by ErikElliott-ynp** [comment]
## Welcome page
~~1. Add live link~~
## MVPs
~~1. make MVPs h3 tags
2. add 1-2 bullet points for each MVP~~
## Schema
~~1. table names lowercase and snake_case
2. remove recently played (possible joins table)
3. Add indexes on playlist columns
4. Add year to albums
5. remove indexes on `id`s and make separate bullet points
6. remove genre tables
7. description on playlists~~
## Sample state
~~1. camelCase Keys
2. check the commas
3. remove recentlyPlayed
4. No playlist errors
5. add currentSong slice of state~~
~~6. add mediaUrls to correct slices~~
~~7. check formatting
8. make sure keys are plural `songs` `albums`~~
## Backend routes
~~1. get rid of users index
2. remove first playlist route~~
~~3. :id on playlist update~~
~~4. no song routes (do all the fetching in playlists/albums/artists)
5. remove album index~~
~~6. all wildcards should just be `:id`~~
## Frontend routes
~~1. song player component
~~2. sidebar component
3. home component
4. artist show
5. album show~~
6. add `:`s to album and artist show pages~~

**Comment by ErikElliott-ynp** [comment]
All done!
